version: '3'

services:
  db:
    image: "microsoft/mssql-server-windows-express"
    environment:
        SA_PASSWORD: "A2C.NetMS"
        ACCEPT_EULA: "Y"
    ports:
      - "1401:1433"
  store.api:
    image: storeapi
    build:
      context: .
      dockerfile: Store.Api\Dockerfile
    depends_on:
      - "db"
    environment:
      - "ConnectionStrings:WebAppSampleContext=Server=db;Database=RzDb;Integrated Security=False;User ID=sa;Password=A2C.NetMS;Connect Timeout=15;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;MultiSubnetFailover=False"
  
