// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Store.Infra.StoreContext.DataContext;
using System;

namespace Store.Infra.Migrations
{
    [DbContext(typeof(StoreDataContext))]
    partial class StoreDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Store.Domain.Context.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Store.Domain.Context.Entities.User", b =>
                {
                    b.OwnsOne("Store.Domain.StoreContext.VO.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId");

                            b1.Property<string>("Text");

                            b1.ToTable("Users");

                            b1.HasOne("Store.Domain.Context.Entities.User")
                                .WithOne("Email")
                                .HasForeignKey("Store.Domain.StoreContext.VO.Email", "UserId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("Store.Domain.StoreContext.VO.FullName", "FullName", b1 =>
                        {
                            b1.Property<Guid>("UserId");

                            b1.Property<string>("Text");

                            b1.ToTable("Users");

                            b1.HasOne("Store.Domain.Context.Entities.User")
                                .WithOne("FullName")
                                .HasForeignKey("Store.Domain.StoreContext.VO.FullName", "UserId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("Store.Domain.StoreContext.VO.Password", "Password", b1 =>
                        {
                            b1.Property<Guid>("UserId");

                            b1.Property<string>("Text");

                            b1.ToTable("Users");

                            b1.HasOne("Store.Domain.Context.Entities.User")
                                .WithOne("Password")
                                .HasForeignKey("Store.Domain.StoreContext.VO.Password", "UserId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("Store.Domain.StoreContext.VO.UserName", "UserName", b1 =>
                        {
                            b1.Property<Guid>("UserId");

                            b1.Property<string>("Text");

                            b1.ToTable("Users");

                            b1.HasOne("Store.Domain.Context.Entities.User")
                                .WithOne("UserName")
                                .HasForeignKey("Store.Domain.StoreContext.VO.UserName", "UserId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
